version: "3"
services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  backend:
    build: .
    command: /bin/bash -l -c "sudo rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes: 
      - ./backend:/home/hosting/blog
    depends_on:
      - db
    ports:
      - "3000:3000"
volumes:
  postgres:
